In [ ]:
pip install ibge

#Sugest√µes Professor

#flatten_json
#https://pypi.org/project/swifter/

In [1]:
### Bibliotecas

import requests
import json
import pandas as pd
import numpy as np
import ibge

In [ ]:
#buscas

t ='https://servicodados.ibge.gov.br/api/v3/agregados?assunto=118'
t2 = 'https://servicodados.ibge.gov.br/api/v3/agregados/5797/periodos'
t3 = 'https://servicodados.ibge.gov.br/api/v3/agregados/5797/metadados'

tt = requests.get(t).json()
ttt = requests.get(t2).json()
tttt = requests.get(t3).json()

ttt

In [2]:
#pesquisas escolhidas

url = 'https://servicodados.ibge.gov.br/api/v3/agregados/7310/periodos/2019/variaveis/10616?localidades=N3[all]&classificacao=951[all]'
url2 = 'https://servicodados.ibge.gov.br/api/v3/agregados/7339/periodos/2019/variaveis/162|10250?localidades=N2[all]&classificacao=687[48521]'
url3 = 'https://servicodados.ibge.gov.br/api/v3/agregados/7395/periodos/2019/variaveis/10686?localidades=N7[all]'

dom_sem_acesso_intenet = requests.get(url).json()
dom_com_pc_tablet = requests.get(url2).json()
dom_rend_perc = requests.get(url3).json()

#df_1 = pd.read_json(url)
#df_2 = pd.read_json(url2)
#df_3 = pd.read_json(url3)
df_4 = pd.DataFrame(data=dom_sem_acesso_intenet[0]['resultados'][0]['series'])
df_5 = pd.DataFrame(data=dom_com_pc_tablet[0]['resultados'][0]['series'])
df_6 = pd.DataFrame(data=dom_rend_perc[0]['resultados'][0]['series'])

In [7]:
df_4

                                           localidade             serie
0   {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Un...    {'2019': '88'}
1   {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Un...    {'2019': '75'}
2   {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '229'}
3   {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Un...    {'2019': '31'}
4   {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '647'}
5   {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Un...    {'2019': '35'}
6   {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '121'}
7   {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '643'}
8   {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '314'}
9   {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '699'}
10  {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '230'}
11  {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '282'}
12  {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '756'}
13  {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '271'}
14  {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '140'}
15  {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Un...  {'2019': '1152'}
16  {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Un...  {'2019': '1150'}
17  {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '193'}
18  {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '751'}
19  {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Un...  {'2019': '1439'}
20  {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '557'}
21  {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '294'}
22  {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '596'}
23  {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '108'}
24  {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '157'}
25  {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Un...   {'2019': '358'}
26  {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Un...    {'2019': '50'}

In [ ]:
### dados paises

p = 'https://servicodados.ibge.gov.br/api/v1/paises/'
paises = requests.get(p).json()

cods = []
for n in range(300):
    try: 
        cods.append(paises[n]['id']['ISO-3166-1-ALPHA-2'])
    except:
        break

paises = []
for n in range(300):
    try: 
        paises.append(paises[n]['nome']['abreviado'])
    except:
        break
        
pib=[]

for n in range(len(cods)):
    d=requests.get('https://servicodados.ibge.gov.br/api/v1/paises/'+cods[n]+'/indicadores/77823')
    pib.append(d[0]['series'][0]['serie'][-2])

In [ ]:
d=requests.get('https://servicodados.ibge.gov.br/api/v1/paises/BR/indicadores/77823').json()
d[0]['series'][0]['pais']['id']
str(d[0]['series'][0]['serie'] [-2].values())